// tests go here; this will not be compiled when this package is used as an extension.
mShield.irCallBack(function () {
    if (mShield.irButton(mShield.MshieldIrButtons.Number1)) {
        mShield.setLed(mShield.LEDs.LED20, mShield.LedState.ON)
        mShield.setLed(mShield.LEDs.LED40, mShield.LedState.ON)
        mShield.setLed(mShield.LEDs.LED60, mShield.LedState.ON)
        mShield.setLed(mShield.LEDs.LED80, mShield.LedState.ON)
        basic.pause(1000)
    }
    if (mShield.irButton(mShield.MshieldIrButtons.Number2)) {
        mShield.turnOffAllLeds()
        basic.pause(1000)
    }
})
mShield.motorsAdjustment(0, 0)
basic.forever(function () {
    mShield.setMotorsDirectionSpeed(mShield.Motors.AllMotors, mShield.MotorsDirection.CC, 100)
    basic.pause(1000)
    mShield.setMotorsDirectionSpeed(mShield.Motors.AllMotors, mShield.MotorsDirection.CC, 0)
    basic.pause(1000)
    mShield.setMotorsDirectionSpeed(mShield.Motors.AllMotors, mShield.MotorsDirection.CCW, 100)
    basic.pause(1000)
    mShield.setMotorsDirectionSpeed(mShield.Motors.AllMotors, mShield.MotorsDirection.CCW, 0)
    basic.pause(1000)
    mShield.setS1ToS4Type(mShield.S1ToS4Type.PWM)
    basic.pause(1000)
    mShield.extendPwmControl(mShield.PwmIndex.S1, 200)
    mShield.extendPwmControl(mShield.PwmIndex.S2, 200)
    mShield.extendPwmControl(mShield.PwmIndex.S3, 200)
    mShield.extendPwmControl(mShield.PwmIndex.S4, 200)
    basic.pause(1000)
    mShield.extendPwmControl(mShield.PwmIndex.S1, 0)
    mShield.extendPwmControl(mShield.PwmIndex.S2, 0)
    mShield.extendPwmControl(mShield.PwmIndex.S3, 0)
    mShield.extendPwmControl(mShield.PwmIndex.S4, 0)
    basic.pause(1000)
    mShield.setS1ToS4Type(mShield.S1ToS4Type.Servo)
    basic.pause(1000)
    mShield.extendServoControl(mShield.ServoIndex.S1, mShield.ServoType.Servo180, 0)
    mShield.extendServoControl(mShield.ServoIndex.S2, mShield.ServoType.Servo180, 0)
    mShield.extendServoControl(mShield.ServoIndex.S3, mShield.ServoType.Servo180, 0)
    mShield.extendServoControl(mShield.ServoIndex.S4, mShield.ServoType.Servo180, 0)
    basic.pause(1000)
    mShield.extendServoControl(mShield.ServoIndex.S1, mShield.ServoType.Servo180, 180)
    mShield.extendServoControl(mShield.ServoIndex.S2, mShield.ServoType.Servo180, 180)
    mShield.extendServoControl(mShield.ServoIndex.S3, mShield.ServoType.Servo180, 180)
    mShield.extendServoControl(mShield.ServoIndex.S4, mShield.ServoType.Servo180, 180)
    basic.pause(1000)
    mShield.continuousServoControl(mShield.ServoIndex.S1, 100)
    basic.pause(1000)
    mShield.continuousServoControl(mShield.ServoIndex.S1, 0)
    basic.pause(1000)
    mShield.continuousServoControl(mShield.ServoIndex.S1, -100)
    basic.pause(1000)
    mShield.continuousServoControl(mShield.ServoIndex.S1, 0)
    basic.pause(1000)
    basic.showNumber(mShield.batteryLevel(mShield.BatteryType.AA3))
    basic.pause(1000)
    basic.showString(mShield.readVersions())
})